apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component-name: redis
    spec:
      containers:
        - name: redis
          image: redis:3-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: http
