apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component-name: frontend
    spec:
      containers:
        - name: frontend
          image: mkorman/cndsr-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
