apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: endpoint
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component-name: endpoint
    spec:
      containers:
        - name: frontend
          image: mkorman/cndsr-endpoint:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
