language: python
sudo: required
python:
  - 3.6
services:
  - docker

install:
  - if [[ "$TRAVIS_BRANCH" == "release-"* ]]; then
    export VERSION="$(echo $TRAVIS_BRANCH | cut -d "-" -f 2)";
    else export VERSION="$TRAVIS_BRANCH";
    fi
  - make config

script:
  - make
  - make validate

after_success:
  - if [[ "$TRAVIS_BRANCH" == "release-"* ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push mkorman/django-url-shortening-backend:$VERSION && docker push mkorman/django-url-shortening-backend:latest;
    fi

branches:
  only:
    - /^(?!untagged-).*$/

notifications:
  email: false
