version: '3'
services:
  redis:
    image: redis:3-alpine
    ports:
      - "6379"

  backend:
    image: mkorman/cndsr-backend:latest
    ports:
      - "8080"
    environment:
      - REDIS_SERVICE_HOST=redis
      - REDIS_SERVICE_PORT=6379
    depends_on:
      - redis

  endpoint:
    image: mkorman/cndsr-endpoint:latest
    ports:
      - "8080"
    environment:
      - BACKEND_SERVICE_HOST=backend
      - BACKEND_SERVICE_PORT=8080
    depends_on:
      - backend

  feature-tests:
    image: mkorman/cndsr-feature-tests:latest
    environment:
      - ENDPOINT_SERVICE_HOST=endpoint
      - ENDPOINT_SERVICE_PORT=8080
    depends_on:
      - endpoint
